on: [push]

jobs:
    test-composite-action:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:

          - uses: actions/checkout@v4

          - id: hello-world
            uses: alanjose10/hello-world-composite-action@v1.3
            with:
                who-to-greet: 'Mona the Octocat'
          
          - name: Print the generated random number
            run: echo "The random number is ${{ steps.hello-world.outputs.random-number }}"

    test-docker-action:
      runs-on: ubuntu-latest
      name: A job to test the docker action
      steps:
        - name: Hello world action step
          id: hello
          uses: alanjose10/hello-world-docker-action@v1
          with:
            who-to-greet: 'Mona the Octocat'
        
        - name: Get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"